//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrabRead
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30514-0828")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Adres", Namespace="http://schemas.datacontract.org/2004/07/Gisvl.CrabDecentraal.Domain")]
    internal partial class Adres : object
    {
        
        private CrabRead.Gebouw[] GebouwenField;
        
        private CrabRead.Perceel[] PercelenField;
        
        private CrabRead.RrAdres[] RrAdressenField;
        
        private string appnummerField;
        
        private System.DateTime begindatumField;
        
        private string busnummerField;
        
        private System.Nullable<System.DateTime> einddatumField;
        
        private string gemeenteField;
        
        private string herkomstField;
        
        private string huisnummerField;
        
        private int idField;
        
        private string postcodeField;
        
        private string statusField;
        
        private string straatnaamField;
        
        private string wktField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal CrabRead.Gebouw[] Gebouwen
        {
            get
            {
                return this.GebouwenField;
            }
            set
            {
                this.GebouwenField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal CrabRead.Perceel[] Percelen
        {
            get
            {
                return this.PercelenField;
            }
            set
            {
                this.PercelenField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal CrabRead.RrAdres[] RrAdressen
        {
            get
            {
                return this.RrAdressenField;
            }
            set
            {
                this.RrAdressenField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string appnummer
        {
            get
            {
                return this.appnummerField;
            }
            set
            {
                this.appnummerField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal System.DateTime begindatum
        {
            get
            {
                return this.begindatumField;
            }
            set
            {
                this.begindatumField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string busnummer
        {
            get
            {
                return this.busnummerField;
            }
            set
            {
                this.busnummerField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal System.Nullable<System.DateTime> einddatum
        {
            get
            {
                return this.einddatumField;
            }
            set
            {
                this.einddatumField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string gemeente
        {
            get
            {
                return this.gemeenteField;
            }
            set
            {
                this.gemeenteField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string herkomst
        {
            get
            {
                return this.herkomstField;
            }
            set
            {
                this.herkomstField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string huisnummer
        {
            get
            {
                return this.huisnummerField;
            }
            set
            {
                this.huisnummerField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal int id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string postcode
        {
            get
            {
                return this.postcodeField;
            }
            set
            {
                this.postcodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string status
        {
            get
            {
                return this.statusField;
            }
            set
            {
                this.statusField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string straatnaam
        {
            get
            {
                return this.straatnaamField;
            }
            set
            {
                this.straatnaamField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string wkt
        {
            get
            {
                return this.wktField;
            }
            set
            {
                this.wktField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30514-0828")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Gebouw", Namespace="http://schemas.datacontract.org/2004/07/Gisvl.CrabDecentraal.Domain")]
    internal partial class Gebouw : object
    {
        
        private CrabRead.Adres[] AdressenField;
        
        private string aardgebouwField;
        
        private System.DateTime begindatumField;
        
        private System.Nullable<System.DateTime> einddatumField;
        
        private string geometriemethodeField;
        
        private int idField;
        
        private string identificatorField;
        
        private string statusField;
        
        private string wktField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal CrabRead.Adres[] Adressen
        {
            get
            {
                return this.AdressenField;
            }
            set
            {
                this.AdressenField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string aardgebouw
        {
            get
            {
                return this.aardgebouwField;
            }
            set
            {
                this.aardgebouwField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal System.DateTime begindatum
        {
            get
            {
                return this.begindatumField;
            }
            set
            {
                this.begindatumField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal System.Nullable<System.DateTime> einddatum
        {
            get
            {
                return this.einddatumField;
            }
            set
            {
                this.einddatumField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string geometriemethode
        {
            get
            {
                return this.geometriemethodeField;
            }
            set
            {
                this.geometriemethodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal int id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string identificator
        {
            get
            {
                return this.identificatorField;
            }
            set
            {
                this.identificatorField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string status
        {
            get
            {
                return this.statusField;
            }
            set
            {
                this.statusField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string wkt
        {
            get
            {
                return this.wktField;
            }
            set
            {
                this.wktField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30514-0828")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Perceel", Namespace="http://schemas.datacontract.org/2004/07/Gisvl.CrabDecentraal.Domain")]
    internal partial class Perceel : object
    {
        
        private CrabRead.Adres[] AdressenField;
        
        private System.DateTime begindatumField;
        
        private string capakeyField;
        
        private System.Nullable<System.DateTime> einddatumField;
        
        private int idField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal CrabRead.Adres[] Adressen
        {
            get
            {
                return this.AdressenField;
            }
            set
            {
                this.AdressenField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal System.DateTime begindatum
        {
            get
            {
                return this.begindatumField;
            }
            set
            {
                this.begindatumField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string capakey
        {
            get
            {
                return this.capakeyField;
            }
            set
            {
                this.capakeyField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal System.Nullable<System.DateTime> einddatum
        {
            get
            {
                return this.einddatumField;
            }
            set
            {
                this.einddatumField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal int id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30514-0828")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RrAdres", Namespace="http://schemas.datacontract.org/2004/07/Gisvl.CrabDecentraal.Domain")]
    internal partial class RrAdres : object
    {
        
        private CrabRead.Adres[] AdressenField;
        
        private System.DateTime begindatumField;
        
        private System.Nullable<System.DateTime> einddatumField;
        
        private int idField;
        
        private string rrhuisnummerField;
        
        private string rrindexField;
        
        private string rrstraatcodeField;
        
        private string subkantoncodeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal CrabRead.Adres[] Adressen
        {
            get
            {
                return this.AdressenField;
            }
            set
            {
                this.AdressenField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal System.DateTime begindatum
        {
            get
            {
                return this.begindatumField;
            }
            set
            {
                this.begindatumField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal System.Nullable<System.DateTime> einddatum
        {
            get
            {
                return this.einddatumField;
            }
            set
            {
                this.einddatumField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal int id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string rrhuisnummer
        {
            get
            {
                return this.rrhuisnummerField;
            }
            set
            {
                this.rrhuisnummerField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string rrindex
        {
            get
            {
                return this.rrindexField;
            }
            set
            {
                this.rrindexField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string rrstraatcode
        {
            get
            {
                return this.rrstraatcodeField;
            }
            set
            {
                this.rrstraatcodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string subkantoncode
        {
            get
            {
                return this.subkantoncodeField;
            }
            set
            {
                this.subkantoncodeField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30514-0828")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FaultDetail", Namespace="http://www.agiv.be/ErrorHandling/2010/04")]
    internal partial class FaultDetail : object
    {
        
        private CrabRead.FaultMessage[] MessagesField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        internal CrabRead.FaultMessage[] Messages
        {
            get
            {
                return this.MessagesField;
            }
            set
            {
                this.MessagesField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30514-0828")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FaultMessage", Namespace="http://www.agiv.be/ErrorHandling/2010/04")]
    internal partial class FaultMessage : object
    {
        
        private string SourceField;
        
        private string TagField;
        
        private CrabRead.MessageText[] TranslationsField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string Source
        {
            get
            {
                return this.SourceField;
            }
            set
            {
                this.SourceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        internal string Tag
        {
            get
            {
                return this.TagField;
            }
            set
            {
                this.TagField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        internal CrabRead.MessageText[] Translations
        {
            get
            {
                return this.TranslationsField;
            }
            set
            {
                this.TranslationsField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30514-0828")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MessageText", Namespace="http://www.agiv.be/ErrorHandling/2010/04")]
    internal partial class MessageText : object
    {
        
        private string CultureField;
        
        private string TextField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        internal string Culture
        {
            get
            {
                return this.CultureField;
            }
            set
            {
                this.CultureField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        internal string Text
        {
            get
            {
                return this.TextField;
            }
            set
            {
                this.TextField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30514-0828")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Straat", Namespace="http://schemas.datacontract.org/2004/07/Gisvl.CrabDecentraal.Domain")]
    internal partial class Straat : object
    {
        
        private CrabRead.RrStraat[] RrStratenField;
        
        private CrabRead.Wegverbinding[] WegverbindingenLinksField;
        
        private CrabRead.Wegverbinding[] WegverbindingenRechtsField;
        
        private System.DateTime begindatumField;
        
        private System.Nullable<System.DateTime> einddatumField;
        
        private string gemeenteField;
        
        private int idField;
        
        private string statusField;
        
        private int straatcodeField;
        
        private string straatnaamField;
        
        private string straatnaam2Field;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal CrabRead.RrStraat[] RrStraten
        {
            get
            {
                return this.RrStratenField;
            }
            set
            {
                this.RrStratenField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal CrabRead.Wegverbinding[] WegverbindingenLinks
        {
            get
            {
                return this.WegverbindingenLinksField;
            }
            set
            {
                this.WegverbindingenLinksField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal CrabRead.Wegverbinding[] WegverbindingenRechts
        {
            get
            {
                return this.WegverbindingenRechtsField;
            }
            set
            {
                this.WegverbindingenRechtsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal System.DateTime begindatum
        {
            get
            {
                return this.begindatumField;
            }
            set
            {
                this.begindatumField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal System.Nullable<System.DateTime> einddatum
        {
            get
            {
                return this.einddatumField;
            }
            set
            {
                this.einddatumField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string gemeente
        {
            get
            {
                return this.gemeenteField;
            }
            set
            {
                this.gemeenteField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal int id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string status
        {
            get
            {
                return this.statusField;
            }
            set
            {
                this.statusField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal int straatcode
        {
            get
            {
                return this.straatcodeField;
            }
            set
            {
                this.straatcodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string straatnaam
        {
            get
            {
                return this.straatnaamField;
            }
            set
            {
                this.straatnaamField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string straatnaam2
        {
            get
            {
                return this.straatnaam2Field;
            }
            set
            {
                this.straatnaam2Field = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30514-0828")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RrStraat", Namespace="http://schemas.datacontract.org/2004/07/Gisvl.CrabDecentraal.Domain")]
    internal partial class RrStraat : object
    {
        
        private CrabRead.Straat StraatField;
        
        private System.DateTime begindatumField;
        
        private System.Nullable<System.DateTime> einddatumField;
        
        private int idField;
        
        private string rrstraatcodeField;
        
        private int straatidField;
        
        private string subkantoncodeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal CrabRead.Straat Straat
        {
            get
            {
                return this.StraatField;
            }
            set
            {
                this.StraatField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal System.DateTime begindatum
        {
            get
            {
                return this.begindatumField;
            }
            set
            {
                this.begindatumField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal System.Nullable<System.DateTime> einddatum
        {
            get
            {
                return this.einddatumField;
            }
            set
            {
                this.einddatumField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal int id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string rrstraatcode
        {
            get
            {
                return this.rrstraatcodeField;
            }
            set
            {
                this.rrstraatcodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal int straatid
        {
            get
            {
                return this.straatidField;
            }
            set
            {
                this.straatidField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string subkantoncode
        {
            get
            {
                return this.subkantoncodeField;
            }
            set
            {
                this.subkantoncodeField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30514-0828")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Wegverbinding", Namespace="http://schemas.datacontract.org/2004/07/Gisvl.CrabDecentraal.Domain")]
    internal partial class Wegverbinding : object
    {
        
        private CrabRead.Straat StraatLinksField;
        
        private CrabRead.Straat StraatRechtsField;
        
        private System.DateTime begindatumField;
        
        private string eerstehuisnummerlinksField;
        
        private string eerstehuisnummerrechtsField;
        
        private System.Nullable<System.DateTime> einddatumField;
        
        private string geometriemethodeField;
        
        private int idField;
        
        private string identificatorField;
        
        private string laatstehuisnummerlinksField;
        
        private string laatstehuisnummerrechtsField;
        
        private string morfologieField;
        
        private string pariteitlinksField;
        
        private string pariteitrechtsField;
        
        private string statusField;
        
        private System.Nullable<int> straatidlinksField;
        
        private System.Nullable<int> straatidrechtsField;
        
        private string uniqueIDField;
        
        private string verhardingField;
        
        private string wktField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal CrabRead.Straat StraatLinks
        {
            get
            {
                return this.StraatLinksField;
            }
            set
            {
                this.StraatLinksField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal CrabRead.Straat StraatRechts
        {
            get
            {
                return this.StraatRechtsField;
            }
            set
            {
                this.StraatRechtsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal System.DateTime begindatum
        {
            get
            {
                return this.begindatumField;
            }
            set
            {
                this.begindatumField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string eerstehuisnummerlinks
        {
            get
            {
                return this.eerstehuisnummerlinksField;
            }
            set
            {
                this.eerstehuisnummerlinksField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string eerstehuisnummerrechts
        {
            get
            {
                return this.eerstehuisnummerrechtsField;
            }
            set
            {
                this.eerstehuisnummerrechtsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal System.Nullable<System.DateTime> einddatum
        {
            get
            {
                return this.einddatumField;
            }
            set
            {
                this.einddatumField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string geometriemethode
        {
            get
            {
                return this.geometriemethodeField;
            }
            set
            {
                this.geometriemethodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal int id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string identificator
        {
            get
            {
                return this.identificatorField;
            }
            set
            {
                this.identificatorField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string laatstehuisnummerlinks
        {
            get
            {
                return this.laatstehuisnummerlinksField;
            }
            set
            {
                this.laatstehuisnummerlinksField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string laatstehuisnummerrechts
        {
            get
            {
                return this.laatstehuisnummerrechtsField;
            }
            set
            {
                this.laatstehuisnummerrechtsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string morfologie
        {
            get
            {
                return this.morfologieField;
            }
            set
            {
                this.morfologieField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string pariteitlinks
        {
            get
            {
                return this.pariteitlinksField;
            }
            set
            {
                this.pariteitlinksField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string pariteitrechts
        {
            get
            {
                return this.pariteitrechtsField;
            }
            set
            {
                this.pariteitrechtsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string status
        {
            get
            {
                return this.statusField;
            }
            set
            {
                this.statusField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal System.Nullable<int> straatidlinks
        {
            get
            {
                return this.straatidlinksField;
            }
            set
            {
                this.straatidlinksField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal System.Nullable<int> straatidrechts
        {
            get
            {
                return this.straatidrechtsField;
            }
            set
            {
                this.straatidrechtsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string uniqueID
        {
            get
            {
                return this.uniqueIDField;
            }
            set
            {
                this.uniqueIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string verharding
        {
            get
            {
                return this.verhardingField;
            }
            set
            {
                this.verhardingField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string wkt
        {
            get
            {
                return this.wktField;
            }
            set
            {
                this.wktField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30514-0828")]
    [System.Runtime.Serialization.DataContractAttribute(Name="QueryObject", Namespace="http://Gisvl.CrabDecentraal.CrabRead")]
    internal partial class QueryObject : object
    {
        
        private CrabRead.Criterium CriteriumField;
        
        private string GemeenteField;
        
        private int MaxResultsField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal CrabRead.Criterium Criterium
        {
            get
            {
                return this.CriteriumField;
            }
            set
            {
                this.CriteriumField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string Gemeente
        {
            get
            {
                return this.GemeenteField;
            }
            set
            {
                this.GemeenteField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal int MaxResults
        {
            get
            {
                return this.MaxResultsField;
            }
            set
            {
                this.MaxResultsField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30514-0828")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Criterium", Namespace="http://Gisvl.CrabDecentraal.CrabRead")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(CrabRead.Predicate))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(CrabRead.CriteriaCombination))]
    internal partial class Criterium : object
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30514-0828")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Predicate", Namespace="http://Gisvl.CrabDecentraal.CrabRead")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(CrabRead.QueryObject))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(CrabRead.Criterium))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(CrabRead.ComparisonOperator))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(CrabRead.CriteriaCombination))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(CrabRead.Adres[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(CrabRead.Adres))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(CrabRead.Gebouw[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(CrabRead.Gebouw))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(CrabRead.Perceel[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(CrabRead.Perceel))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(CrabRead.RrAdres[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(CrabRead.RrAdres))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(CrabRead.Straat[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(CrabRead.Straat))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(CrabRead.RrStraat[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(CrabRead.RrStraat))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(CrabRead.Wegverbinding[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(CrabRead.Wegverbinding))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(CrabRead.LogicalOperator))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(string[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(CrabRead.FaultDetail))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(CrabRead.FaultMessage[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(CrabRead.FaultMessage))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(CrabRead.MessageText[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(CrabRead.MessageText))]
    internal partial class Predicate : CrabRead.Criterium
    {
        
        private CrabRead.ComparisonOperator ComparisonOperatorField;
        
        private string FieldNameField;
        
        private object ValueField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal CrabRead.ComparisonOperator ComparisonOperator
        {
            get
            {
                return this.ComparisonOperatorField;
            }
            set
            {
                this.ComparisonOperatorField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string FieldName
        {
            get
            {
                return this.FieldNameField;
            }
            set
            {
                this.FieldNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal object Value
        {
            get
            {
                return this.ValueField;
            }
            set
            {
                this.ValueField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30514-0828")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CriteriaCombination", Namespace="http://Gisvl.CrabDecentraal.CrabRead")]
    internal partial class CriteriaCombination : CrabRead.Criterium
    {
        
        private CrabRead.Criterium Criterium1Field;
        
        private CrabRead.Criterium Criterium2Field;
        
        private CrabRead.LogicalOperator LogicalOperatorField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal CrabRead.Criterium Criterium1
        {
            get
            {
                return this.Criterium1Field;
            }
            set
            {
                this.Criterium1Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal CrabRead.Criterium Criterium2
        {
            get
            {
                return this.Criterium2Field;
            }
            set
            {
                this.Criterium2Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal CrabRead.LogicalOperator LogicalOperator
        {
            get
            {
                return this.LogicalOperatorField;
            }
            set
            {
                this.LogicalOperatorField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30514-0828")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ComparisonOperator", Namespace="http://Gisvl.CrabDecentraal.CrabRead")]
    internal enum ComparisonOperator : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        EqualTo = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NotEqualTo = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        LessThan = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        LessThanEqualTo = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        GreaterThan = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        GreaterThanEqualTo = 5,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        IsNull = 6,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        IsNotNull = 7,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Like = 8,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30514-0828")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LogicalOperator", Namespace="http://schemas.datacontract.org/2004/07/Gisvl.CrabDecentraal.ReadContract")]
    internal enum LogicalOperator : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        And = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Or = 1,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30514-0828")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://Gisvl.CrabDecentraal.CrabRead", ConfigurationName="CrabRead.ICrabRead")]
    internal interface ICrabRead
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Gisvl.CrabDecentraal.CrabRead/ICrabRead/FindAdres", ReplyAction="http://Gisvl.CrabDecentraal.CrabRead/ICrabRead/FindAdresResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(CrabRead.FaultDetail), Action="http://Gisvl.CrabDecentraal.CrabRead/ICrabRead/FindAdresFaultDetailFault", Name="FaultDetail", Namespace="http://www.agiv.be/ErrorHandling/2010/04")]
        System.Threading.Tasks.Task<CrabRead.Adres[]> FindAdresAsync(string gemeente, string straatnaam, string postcode, string huisnummer, string busnummer, string appnummer, string herkomst);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Gisvl.CrabDecentraal.CrabRead/ICrabRead/FindGebouw", ReplyAction="http://Gisvl.CrabDecentraal.CrabRead/ICrabRead/FindGebouwResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(CrabRead.FaultDetail), Action="http://Gisvl.CrabDecentraal.CrabRead/ICrabRead/FindGebouwFaultDetailFault", Name="FaultDetail", Namespace="http://www.agiv.be/ErrorHandling/2010/04")]
        System.Threading.Tasks.Task<CrabRead.Gebouw[]> FindGebouwAsync(string identificator, string gemeente, string straatnaam, string postcode, string huisnummer);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Gisvl.CrabDecentraal.CrabRead/ICrabRead/FindPerceel", ReplyAction="http://Gisvl.CrabDecentraal.CrabRead/ICrabRead/FindPerceelResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(CrabRead.FaultDetail), Action="http://Gisvl.CrabDecentraal.CrabRead/ICrabRead/FindPerceelFaultDetailFault", Name="FaultDetail", Namespace="http://www.agiv.be/ErrorHandling/2010/04")]
        System.Threading.Tasks.Task<CrabRead.Perceel[]> FindPerceelAsync(string capakey, string gemeente, string straatnaam, string postcode, string huisnummer);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Gisvl.CrabDecentraal.CrabRead/ICrabRead/FindStraat", ReplyAction="http://Gisvl.CrabDecentraal.CrabRead/ICrabRead/FindStraatResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(CrabRead.FaultDetail), Action="http://Gisvl.CrabDecentraal.CrabRead/ICrabRead/FindStraatFaultDetailFault", Name="FaultDetail", Namespace="http://www.agiv.be/ErrorHandling/2010/04")]
        System.Threading.Tasks.Task<CrabRead.Straat[]> FindStraatAsync(string gemeente, string straatnaam);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Gisvl.CrabDecentraal.CrabRead/ICrabRead/FindWegverbinding", ReplyAction="http://Gisvl.CrabDecentraal.CrabRead/ICrabRead/FindWegverbindingResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(CrabRead.FaultDetail), Action="http://Gisvl.CrabDecentraal.CrabRead/ICrabRead/FindWegverbindingFaultDetailFault", Name="FaultDetail", Namespace="http://www.agiv.be/ErrorHandling/2010/04")]
        System.Threading.Tasks.Task<CrabRead.Wegverbinding[]> FindWegverbindingAsync(string identificator, string gemeente, string straatnaam);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Gisvl.CrabDecentraal.CrabRead/ICrabRead/GetAdres", ReplyAction="http://Gisvl.CrabDecentraal.CrabRead/ICrabRead/GetAdresResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(CrabRead.FaultDetail), Action="http://Gisvl.CrabDecentraal.CrabRead/ICrabRead/GetAdresFaultDetailFault", Name="FaultDetail", Namespace="http://www.agiv.be/ErrorHandling/2010/04")]
        System.Threading.Tasks.Task<CrabRead.Adres> GetAdresAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Gisvl.CrabDecentraal.CrabRead/ICrabRead/GetGebouw", ReplyAction="http://Gisvl.CrabDecentraal.CrabRead/ICrabRead/GetGebouwResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(CrabRead.FaultDetail), Action="http://Gisvl.CrabDecentraal.CrabRead/ICrabRead/GetGebouwFaultDetailFault", Name="FaultDetail", Namespace="http://www.agiv.be/ErrorHandling/2010/04")]
        System.Threading.Tasks.Task<CrabRead.Gebouw> GetGebouwAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Gisvl.CrabDecentraal.CrabRead/ICrabRead/GetPerceel", ReplyAction="http://Gisvl.CrabDecentraal.CrabRead/ICrabRead/GetPerceelResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(CrabRead.FaultDetail), Action="http://Gisvl.CrabDecentraal.CrabRead/ICrabRead/GetPerceelFaultDetailFault", Name="FaultDetail", Namespace="http://www.agiv.be/ErrorHandling/2010/04")]
        System.Threading.Tasks.Task<CrabRead.Perceel> GetPerceelAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Gisvl.CrabDecentraal.CrabRead/ICrabRead/GetStraat", ReplyAction="http://Gisvl.CrabDecentraal.CrabRead/ICrabRead/GetStraatResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(CrabRead.FaultDetail), Action="http://Gisvl.CrabDecentraal.CrabRead/ICrabRead/GetStraatFaultDetailFault", Name="FaultDetail", Namespace="http://www.agiv.be/ErrorHandling/2010/04")]
        System.Threading.Tasks.Task<CrabRead.Straat> GetStraatAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Gisvl.CrabDecentraal.CrabRead/ICrabRead/GetWegverbinding", ReplyAction="http://Gisvl.CrabDecentraal.CrabRead/ICrabRead/GetWegverbindingResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(CrabRead.FaultDetail), Action="http://Gisvl.CrabDecentraal.CrabRead/ICrabRead/GetWegverbindingFaultDetailFault", Name="FaultDetail", Namespace="http://www.agiv.be/ErrorHandling/2010/04")]
        System.Threading.Tasks.Task<CrabRead.Wegverbinding> GetWegverbindingAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Gisvl.CrabDecentraal.CrabRead/ICrabRead/GetWegverbindingen", ReplyAction="http://Gisvl.CrabDecentraal.CrabRead/ICrabRead/GetWegverbindingenResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(CrabRead.FaultDetail), Action="http://Gisvl.CrabDecentraal.CrabRead/ICrabRead/GetWegverbindingenFaultDetailFault" +
            "", Name="FaultDetail", Namespace="http://www.agiv.be/ErrorHandling/2010/04")]
        System.Threading.Tasks.Task<CrabRead.Wegverbinding[]> GetWegverbindingenAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Gisvl.CrabDecentraal.CrabRead/ICrabRead/ListGemeente", ReplyAction="http://Gisvl.CrabDecentraal.CrabRead/ICrabRead/ListGemeenteResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(CrabRead.FaultDetail), Action="http://Gisvl.CrabDecentraal.CrabRead/ICrabRead/ListGemeenteFaultDetailFault", Name="FaultDetail", Namespace="http://www.agiv.be/ErrorHandling/2010/04")]
        System.Threading.Tasks.Task<string[]> ListGemeenteAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Gisvl.CrabDecentraal.CrabRead/ICrabRead/ListPostcodeByGemeente", ReplyAction="http://Gisvl.CrabDecentraal.CrabRead/ICrabRead/ListPostcodeByGemeenteResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(CrabRead.FaultDetail), Action="http://Gisvl.CrabDecentraal.CrabRead/ICrabRead/ListPostcodeByGemeenteFaultDetailF" +
            "ault", Name="FaultDetail", Namespace="http://www.agiv.be/ErrorHandling/2010/04")]
        System.Threading.Tasks.Task<string[]> ListPostcodeByGemeenteAsync(string gemeente);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Gisvl.CrabDecentraal.CrabRead/ICrabRead/ListStraatnaamByGemeente", ReplyAction="http://Gisvl.CrabDecentraal.CrabRead/ICrabRead/ListStraatnaamByGemeenteResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(CrabRead.FaultDetail), Action="http://Gisvl.CrabDecentraal.CrabRead/ICrabRead/ListStraatnaamByGemeenteFaultDetai" +
            "lFault", Name="FaultDetail", Namespace="http://www.agiv.be/ErrorHandling/2010/04")]
        System.Threading.Tasks.Task<string[]> ListStraatnaamByGemeenteAsync(string gemeente);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Gisvl.CrabDecentraal.CrabRead/ICrabRead/ListRrStraatcodeByStraatnaam", ReplyAction="http://Gisvl.CrabDecentraal.CrabRead/ICrabRead/ListRrStraatcodeByStraatnaamRespon" +
            "se")]
        [System.ServiceModel.FaultContractAttribute(typeof(CrabRead.FaultDetail), Action="http://Gisvl.CrabDecentraal.CrabRead/ICrabRead/ListRrStraatcodeByStraatnaamFaultD" +
            "etailFault", Name="FaultDetail", Namespace="http://www.agiv.be/ErrorHandling/2010/04")]
        System.Threading.Tasks.Task<string[]> ListRrStraatcodeByStraatnaamAsync(string gemeente, string straatnaam);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Gisvl.CrabDecentraal.CrabRead/ICrabRead/ListDomeinCategorie", ReplyAction="http://Gisvl.CrabDecentraal.CrabRead/ICrabRead/ListDomeinCategorieResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(CrabRead.FaultDetail), Action="http://Gisvl.CrabDecentraal.CrabRead/ICrabRead/ListDomeinCategorieFaultDetailFaul" +
            "t", Name="FaultDetail", Namespace="http://www.agiv.be/ErrorHandling/2010/04")]
        System.Threading.Tasks.Task<string[]> ListDomeinCategorieAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Gisvl.CrabDecentraal.CrabRead/ICrabRead/ListDomeinWaardeByCategorie", ReplyAction="http://Gisvl.CrabDecentraal.CrabRead/ICrabRead/ListDomeinWaardeByCategorieRespons" +
            "e")]
        [System.ServiceModel.FaultContractAttribute(typeof(CrabRead.FaultDetail), Action="http://Gisvl.CrabDecentraal.CrabRead/ICrabRead/ListDomeinWaardeByCategorieFaultDe" +
            "tailFault", Name="FaultDetail", Namespace="http://www.agiv.be/ErrorHandling/2010/04")]
        System.Threading.Tasks.Task<string[]> ListDomeinWaardeByCategorieAsync(string categorie);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Gisvl.CrabDecentraal.CrabRead/ICrabRead/QueryAdres", ReplyAction="http://Gisvl.CrabDecentraal.CrabRead/ICrabRead/QueryAdresResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(CrabRead.FaultDetail), Action="http://Gisvl.CrabDecentraal.CrabRead/ICrabRead/QueryAdresFaultDetailFault", Name="FaultDetail", Namespace="http://www.agiv.be/ErrorHandling/2010/04")]
        System.Threading.Tasks.Task<CrabRead.Adres[]> QueryAdresAsync(CrabRead.QueryObject request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Gisvl.CrabDecentraal.CrabRead/ICrabRead/QueryGebouw", ReplyAction="http://Gisvl.CrabDecentraal.CrabRead/ICrabRead/QueryGebouwResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(CrabRead.FaultDetail), Action="http://Gisvl.CrabDecentraal.CrabRead/ICrabRead/QueryGebouwFaultDetailFault", Name="FaultDetail", Namespace="http://www.agiv.be/ErrorHandling/2010/04")]
        System.Threading.Tasks.Task<CrabRead.Gebouw[]> QueryGebouwAsync(CrabRead.QueryObject request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Gisvl.CrabDecentraal.CrabRead/ICrabRead/QueryPerceel", ReplyAction="http://Gisvl.CrabDecentraal.CrabRead/ICrabRead/QueryPerceelResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(CrabRead.FaultDetail), Action="http://Gisvl.CrabDecentraal.CrabRead/ICrabRead/QueryPerceelFaultDetailFault", Name="FaultDetail", Namespace="http://www.agiv.be/ErrorHandling/2010/04")]
        System.Threading.Tasks.Task<CrabRead.Perceel[]> QueryPerceelAsync(CrabRead.QueryObject request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Gisvl.CrabDecentraal.CrabRead/ICrabRead/QueryStraat", ReplyAction="http://Gisvl.CrabDecentraal.CrabRead/ICrabRead/QueryStraatResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(CrabRead.FaultDetail), Action="http://Gisvl.CrabDecentraal.CrabRead/ICrabRead/QueryStraatFaultDetailFault", Name="FaultDetail", Namespace="http://www.agiv.be/ErrorHandling/2010/04")]
        System.Threading.Tasks.Task<CrabRead.Straat[]> QueryStraatAsync(CrabRead.QueryObject request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Gisvl.CrabDecentraal.CrabRead/ICrabRead/QueryWegverbinding", ReplyAction="http://Gisvl.CrabDecentraal.CrabRead/ICrabRead/QueryWegverbindingResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(CrabRead.FaultDetail), Action="http://Gisvl.CrabDecentraal.CrabRead/ICrabRead/QueryWegverbindingFaultDetailFault" +
            "", Name="FaultDetail", Namespace="http://www.agiv.be/ErrorHandling/2010/04")]
        System.Threading.Tasks.Task<CrabRead.Wegverbinding[]> QueryWegverbindingAsync(CrabRead.QueryObject request);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30514-0828")]
    internal interface ICrabReadChannel : CrabRead.ICrabRead, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30514-0828")]
    internal partial class CrabReadClient : System.ServiceModel.ClientBase<CrabRead.ICrabRead>, CrabRead.ICrabRead
    {
        
        public CrabReadClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<CrabRead.Adres[]> FindAdresAsync(string gemeente, string straatnaam, string postcode, string huisnummer, string busnummer, string appnummer, string herkomst)
        {
            return base.Channel.FindAdresAsync(gemeente, straatnaam, postcode, huisnummer, busnummer, appnummer, herkomst);
        }
        
        public System.Threading.Tasks.Task<CrabRead.Gebouw[]> FindGebouwAsync(string identificator, string gemeente, string straatnaam, string postcode, string huisnummer)
        {
            return base.Channel.FindGebouwAsync(identificator, gemeente, straatnaam, postcode, huisnummer);
        }
        
        public System.Threading.Tasks.Task<CrabRead.Perceel[]> FindPerceelAsync(string capakey, string gemeente, string straatnaam, string postcode, string huisnummer)
        {
            return base.Channel.FindPerceelAsync(capakey, gemeente, straatnaam, postcode, huisnummer);
        }
        
        public System.Threading.Tasks.Task<CrabRead.Straat[]> FindStraatAsync(string gemeente, string straatnaam)
        {
            return base.Channel.FindStraatAsync(gemeente, straatnaam);
        }
        
        public System.Threading.Tasks.Task<CrabRead.Wegverbinding[]> FindWegverbindingAsync(string identificator, string gemeente, string straatnaam)
        {
            return base.Channel.FindWegverbindingAsync(identificator, gemeente, straatnaam);
        }
        
        public System.Threading.Tasks.Task<CrabRead.Adres> GetAdresAsync(int id)
        {
            return base.Channel.GetAdresAsync(id);
        }
        
        public System.Threading.Tasks.Task<CrabRead.Gebouw> GetGebouwAsync(int id)
        {
            return base.Channel.GetGebouwAsync(id);
        }
        
        public System.Threading.Tasks.Task<CrabRead.Perceel> GetPerceelAsync(int id)
        {
            return base.Channel.GetPerceelAsync(id);
        }
        
        public System.Threading.Tasks.Task<CrabRead.Straat> GetStraatAsync(int id)
        {
            return base.Channel.GetStraatAsync(id);
        }
        
        public System.Threading.Tasks.Task<CrabRead.Wegverbinding> GetWegverbindingAsync(int id)
        {
            return base.Channel.GetWegverbindingAsync(id);
        }
        
        public System.Threading.Tasks.Task<CrabRead.Wegverbinding[]> GetWegverbindingenAsync(int id)
        {
            return base.Channel.GetWegverbindingenAsync(id);
        }
        
        public System.Threading.Tasks.Task<string[]> ListGemeenteAsync()
        {
            return base.Channel.ListGemeenteAsync();
        }
        
        public System.Threading.Tasks.Task<string[]> ListPostcodeByGemeenteAsync(string gemeente)
        {
            return base.Channel.ListPostcodeByGemeenteAsync(gemeente);
        }
        
        public System.Threading.Tasks.Task<string[]> ListStraatnaamByGemeenteAsync(string gemeente)
        {
            return base.Channel.ListStraatnaamByGemeenteAsync(gemeente);
        }
        
        public System.Threading.Tasks.Task<string[]> ListRrStraatcodeByStraatnaamAsync(string gemeente, string straatnaam)
        {
            return base.Channel.ListRrStraatcodeByStraatnaamAsync(gemeente, straatnaam);
        }
        
        public System.Threading.Tasks.Task<string[]> ListDomeinCategorieAsync()
        {
            return base.Channel.ListDomeinCategorieAsync();
        }
        
        public System.Threading.Tasks.Task<string[]> ListDomeinWaardeByCategorieAsync(string categorie)
        {
            return base.Channel.ListDomeinWaardeByCategorieAsync(categorie);
        }
        
        public System.Threading.Tasks.Task<CrabRead.Adres[]> QueryAdresAsync(CrabRead.QueryObject request)
        {
            return base.Channel.QueryAdresAsync(request);
        }
        
        public System.Threading.Tasks.Task<CrabRead.Gebouw[]> QueryGebouwAsync(CrabRead.QueryObject request)
        {
            return base.Channel.QueryGebouwAsync(request);
        }
        
        public System.Threading.Tasks.Task<CrabRead.Perceel[]> QueryPerceelAsync(CrabRead.QueryObject request)
        {
            return base.Channel.QueryPerceelAsync(request);
        }
        
        public System.Threading.Tasks.Task<CrabRead.Straat[]> QueryStraatAsync(CrabRead.QueryObject request)
        {
            return base.Channel.QueryStraatAsync(request);
        }
        
        public System.Threading.Tasks.Task<CrabRead.Wegverbinding[]> QueryWegverbindingAsync(CrabRead.QueryObject request)
        {
            return base.Channel.QueryWegverbindingAsync(request);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
    }
}
