//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrabWrite
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30514-0828")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FaultDetail", Namespace="http://www.agiv.be/ErrorHandling/2010/04")]
    internal partial class FaultDetail : object
    {
        
        private CrabWrite.FaultMessage[] MessagesField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        internal CrabWrite.FaultMessage[] Messages
        {
            get
            {
                return this.MessagesField;
            }
            set
            {
                this.MessagesField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30514-0828")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FaultMessage", Namespace="http://www.agiv.be/ErrorHandling/2010/04")]
    internal partial class FaultMessage : object
    {
        
        private string SourceField;
        
        private string TagField;
        
        private CrabWrite.MessageText[] TranslationsField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string Source
        {
            get
            {
                return this.SourceField;
            }
            set
            {
                this.SourceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        internal string Tag
        {
            get
            {
                return this.TagField;
            }
            set
            {
                this.TagField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        internal CrabWrite.MessageText[] Translations
        {
            get
            {
                return this.TranslationsField;
            }
            set
            {
                this.TranslationsField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30514-0828")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MessageText", Namespace="http://www.agiv.be/ErrorHandling/2010/04")]
    internal partial class MessageText : object
    {
        
        private string CultureField;
        
        private string TextField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        internal string Culture
        {
            get
            {
                return this.CultureField;
            }
            set
            {
                this.CultureField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        internal string Text
        {
            get
            {
                return this.TextField;
            }
            set
            {
                this.TextField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30514-0828")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AddStraatRequest", Namespace="http://Gisvl.CrabDecentraal.CrabEdit")]
    internal partial class AddStraatRequest : object
    {
        
        private System.DateTime BegindatumField;
        
        private string GemeenteField;
        
        private CrabWrite.RrStraat[] RrStratenField;
        
        private string StatusField;
        
        private string StraatnaamField;
        
        private string Straatnaam2Field;
        
        private CrabWrite.Wegkant[] WegkantenField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal System.DateTime Begindatum
        {
            get
            {
                return this.BegindatumField;
            }
            set
            {
                this.BegindatumField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string Gemeente
        {
            get
            {
                return this.GemeenteField;
            }
            set
            {
                this.GemeenteField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal CrabWrite.RrStraat[] RrStraten
        {
            get
            {
                return this.RrStratenField;
            }
            set
            {
                this.RrStratenField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string Status
        {
            get
            {
                return this.StatusField;
            }
            set
            {
                this.StatusField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string Straatnaam
        {
            get
            {
                return this.StraatnaamField;
            }
            set
            {
                this.StraatnaamField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string Straatnaam2
        {
            get
            {
                return this.Straatnaam2Field;
            }
            set
            {
                this.Straatnaam2Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal CrabWrite.Wegkant[] Wegkanten
        {
            get
            {
                return this.WegkantenField;
            }
            set
            {
                this.WegkantenField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30514-0828")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RrStraat", Namespace="http://Gisvl.CrabDecentraal.CrabEdit")]
    internal partial class RrStraat : object
    {
        
        private string RrStraatcodeField;
        
        private string SubkantoncodeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string RrStraatcode
        {
            get
            {
                return this.RrStraatcodeField;
            }
            set
            {
                this.RrStraatcodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string Subkantoncode
        {
            get
            {
                return this.SubkantoncodeField;
            }
            set
            {
                this.SubkantoncodeField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30514-0828")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Wegkant", Namespace="http://Gisvl.CrabDecentraal.CrabEdit")]
    internal partial class Wegkant : object
    {
        
        private string EersteHuisnummerLinksField;
        
        private string EersteHuisnummerRechtsField;
        
        private string LaatsteHuisnummerLinksField;
        
        private string LaatsteHuisnummerRechtsField;
        
        private bool LinksField;
        
        private string PariteitLinksField;
        
        private string PariteitRechtsField;
        
        private bool RechtsField;
        
        private CrabWrite.Wegverbinding WegverbindingField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string EersteHuisnummerLinks
        {
            get
            {
                return this.EersteHuisnummerLinksField;
            }
            set
            {
                this.EersteHuisnummerLinksField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string EersteHuisnummerRechts
        {
            get
            {
                return this.EersteHuisnummerRechtsField;
            }
            set
            {
                this.EersteHuisnummerRechtsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string LaatsteHuisnummerLinks
        {
            get
            {
                return this.LaatsteHuisnummerLinksField;
            }
            set
            {
                this.LaatsteHuisnummerLinksField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string LaatsteHuisnummerRechts
        {
            get
            {
                return this.LaatsteHuisnummerRechtsField;
            }
            set
            {
                this.LaatsteHuisnummerRechtsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal bool Links
        {
            get
            {
                return this.LinksField;
            }
            set
            {
                this.LinksField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string PariteitLinks
        {
            get
            {
                return this.PariteitLinksField;
            }
            set
            {
                this.PariteitLinksField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string PariteitRechts
        {
            get
            {
                return this.PariteitRechtsField;
            }
            set
            {
                this.PariteitRechtsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal bool Rechts
        {
            get
            {
                return this.RechtsField;
            }
            set
            {
                this.RechtsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal CrabWrite.Wegverbinding Wegverbinding
        {
            get
            {
                return this.WegverbindingField;
            }
            set
            {
                this.WegverbindingField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30514-0828")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Wegverbinding", Namespace="http://Gisvl.CrabDecentraal.CrabEdit")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(CrabWrite.BestaandeWegverbinding))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(CrabWrite.NieuweWegverbinding))]
    internal partial class Wegverbinding : object
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30514-0828")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BestaandeWegverbinding", Namespace="http://Gisvl.CrabDecentraal.CrabEdit")]
    internal partial class BestaandeWegverbinding : CrabWrite.Wegverbinding
    {
        
        private string IdentificatorField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string Identificator
        {
            get
            {
                return this.IdentificatorField;
            }
            set
            {
                this.IdentificatorField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30514-0828")]
    [System.Runtime.Serialization.DataContractAttribute(Name="NieuweWegverbinding", Namespace="http://Gisvl.CrabDecentraal.CrabEdit")]
    internal partial class NieuweWegverbinding : CrabWrite.Wegverbinding
    {
        
        private System.DateTime BegindatumField;
        
        private string GeometriemethodeField;
        
        private string MorfologieField;
        
        private string StatusField;
        
        private string VerhardingField;
        
        private string WktField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal System.DateTime Begindatum
        {
            get
            {
                return this.BegindatumField;
            }
            set
            {
                this.BegindatumField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string Geometriemethode
        {
            get
            {
                return this.GeometriemethodeField;
            }
            set
            {
                this.GeometriemethodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string Morfologie
        {
            get
            {
                return this.MorfologieField;
            }
            set
            {
                this.MorfologieField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string Status
        {
            get
            {
                return this.StatusField;
            }
            set
            {
                this.StatusField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string Verharding
        {
            get
            {
                return this.VerhardingField;
            }
            set
            {
                this.VerhardingField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string Wkt
        {
            get
            {
                return this.WktField;
            }
            set
            {
                this.WktField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30514-0828")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AddAdresRequest", Namespace="http://Gisvl.CrabDecentraal.CrabEdit")]
    internal partial class AddAdresRequest : object
    {
        
        private System.DateTime BegindatumField;
        
        private CrabWrite.BestaandGebouw[] BestaandeGebouwenField;
        
        private CrabWrite.BestaandPerceel[] BestaandePercelenField;
        
        private string GemeenteField;
        
        private string HuisnummerField;
        
        private CrabWrite.NieuwGebouw[] NieuweGebouwenField;
        
        private CrabWrite.Adrespositie[] PositiesField;
        
        private string PostcodeField;
        
        private CrabWrite.RrAdres RrAdresField;
        
        private string StatusField;
        
        private string StraatnaamField;
        
        private CrabWrite.Subadres[] SubadressenField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal System.DateTime Begindatum
        {
            get
            {
                return this.BegindatumField;
            }
            set
            {
                this.BegindatumField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal CrabWrite.BestaandGebouw[] BestaandeGebouwen
        {
            get
            {
                return this.BestaandeGebouwenField;
            }
            set
            {
                this.BestaandeGebouwenField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal CrabWrite.BestaandPerceel[] BestaandePercelen
        {
            get
            {
                return this.BestaandePercelenField;
            }
            set
            {
                this.BestaandePercelenField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string Gemeente
        {
            get
            {
                return this.GemeenteField;
            }
            set
            {
                this.GemeenteField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string Huisnummer
        {
            get
            {
                return this.HuisnummerField;
            }
            set
            {
                this.HuisnummerField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal CrabWrite.NieuwGebouw[] NieuweGebouwen
        {
            get
            {
                return this.NieuweGebouwenField;
            }
            set
            {
                this.NieuweGebouwenField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal CrabWrite.Adrespositie[] Posities
        {
            get
            {
                return this.PositiesField;
            }
            set
            {
                this.PositiesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string Postcode
        {
            get
            {
                return this.PostcodeField;
            }
            set
            {
                this.PostcodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal CrabWrite.RrAdres RrAdres
        {
            get
            {
                return this.RrAdresField;
            }
            set
            {
                this.RrAdresField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string Status
        {
            get
            {
                return this.StatusField;
            }
            set
            {
                this.StatusField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string Straatnaam
        {
            get
            {
                return this.StraatnaamField;
            }
            set
            {
                this.StraatnaamField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal CrabWrite.Subadres[] Subadressen
        {
            get
            {
                return this.SubadressenField;
            }
            set
            {
                this.SubadressenField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30514-0828")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RrAdres", Namespace="http://Gisvl.CrabDecentraal.CrabEdit")]
    internal partial class RrAdres : object
    {
        
        private string RrHuisnummerField;
        
        private string RrIndexField;
        
        private CrabWrite.RrStraat RrStraatField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string RrHuisnummer
        {
            get
            {
                return this.RrHuisnummerField;
            }
            set
            {
                this.RrHuisnummerField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string RrIndex
        {
            get
            {
                return this.RrIndexField;
            }
            set
            {
                this.RrIndexField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal CrabWrite.RrStraat RrStraat
        {
            get
            {
                return this.RrStraatField;
            }
            set
            {
                this.RrStraatField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30514-0828")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BestaandGebouw", Namespace="http://Gisvl.CrabDecentraal.CrabEdit")]
    internal partial class BestaandGebouw : object
    {
        
        private string IdentificatorField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string Identificator
        {
            get
            {
                return this.IdentificatorField;
            }
            set
            {
                this.IdentificatorField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30514-0828")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BestaandPerceel", Namespace="http://Gisvl.CrabDecentraal.CrabEdit")]
    internal partial class BestaandPerceel : object
    {
        
        private string CapakeyField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string Capakey
        {
            get
            {
                return this.CapakeyField;
            }
            set
            {
                this.CapakeyField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30514-0828")]
    [System.Runtime.Serialization.DataContractAttribute(Name="NieuwGebouw", Namespace="http://Gisvl.CrabDecentraal.CrabEdit")]
    internal partial class NieuwGebouw : object
    {
        
        private string AardGebouwField;
        
        private System.DateTime BegindatumField;
        
        private string GeometriemethodeField;
        
        private string StatusField;
        
        private string WktField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string AardGebouw
        {
            get
            {
                return this.AardGebouwField;
            }
            set
            {
                this.AardGebouwField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal System.DateTime Begindatum
        {
            get
            {
                return this.BegindatumField;
            }
            set
            {
                this.BegindatumField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string Geometriemethode
        {
            get
            {
                return this.GeometriemethodeField;
            }
            set
            {
                this.GeometriemethodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string Status
        {
            get
            {
                return this.StatusField;
            }
            set
            {
                this.StatusField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string Wkt
        {
            get
            {
                return this.WktField;
            }
            set
            {
                this.WktField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30514-0828")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Adrespositie", Namespace="http://Gisvl.CrabDecentraal.CrabEdit")]
    internal partial class Adrespositie : object
    {
        
        private string HerkomstField;
        
        private string WktField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string Herkomst
        {
            get
            {
                return this.HerkomstField;
            }
            set
            {
                this.HerkomstField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string Wkt
        {
            get
            {
                return this.WktField;
            }
            set
            {
                this.WktField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30514-0828")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Subadres", Namespace="http://Gisvl.CrabDecentraal.CrabEdit")]
    internal partial class Subadres : object
    {
        
        private string AppnummerField;
        
        private System.DateTime BegindatumField;
        
        private string BusnummerField;
        
        private CrabWrite.Adrespositie PositieField;
        
        private string RrIndexField;
        
        private string StatusField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string Appnummer
        {
            get
            {
                return this.AppnummerField;
            }
            set
            {
                this.AppnummerField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal System.DateTime Begindatum
        {
            get
            {
                return this.BegindatumField;
            }
            set
            {
                this.BegindatumField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string Busnummer
        {
            get
            {
                return this.BusnummerField;
            }
            set
            {
                this.BusnummerField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal CrabWrite.Adrespositie Positie
        {
            get
            {
                return this.PositieField;
            }
            set
            {
                this.PositieField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string RrIndex
        {
            get
            {
                return this.RrIndexField;
            }
            set
            {
                this.RrIndexField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string Status
        {
            get
            {
                return this.StatusField;
            }
            set
            {
                this.StatusField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30514-0828")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AddGebouwRequest", Namespace="http://Gisvl.CrabDecentraal.CrabEdit")]
    internal partial class AddGebouwRequest : object
    {
        
        private CrabWrite.NieuwGebouw GebouwField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal CrabWrite.NieuwGebouw Gebouw
        {
            get
            {
                return this.GebouwField;
            }
            set
            {
                this.GebouwField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30514-0828")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AddWegverbindingRequest", Namespace="http://Gisvl.CrabDecentraal.CrabEdit")]
    internal partial class AddWegverbindingRequest : object
    {
        
        private CrabWrite.NieuweWegverbinding WegverbindingField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal CrabWrite.NieuweWegverbinding Wegverbinding
        {
            get
            {
                return this.WegverbindingField;
            }
            set
            {
                this.WegverbindingField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30514-0828")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UpdateStraatRequest", Namespace="http://Gisvl.CrabDecentraal.CrabEdit")]
    internal partial class UpdateStraatRequest : object
    {
        
        private System.DateTime BegindatumField;
        
        private int IdField;
        
        private bool IsCorrectieField;
        
        private bool NegeerRrInformatieField;
        
        private CrabWrite.RrStraat[] RrStratenField;
        
        private string StatusField;
        
        private string StraatnaamField;
        
        private string Straatnaam2Field;
        
        private CrabWrite.Wegkant[] WegkantenField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal System.DateTime Begindatum
        {
            get
            {
                return this.BegindatumField;
            }
            set
            {
                this.BegindatumField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal int Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal bool IsCorrectie
        {
            get
            {
                return this.IsCorrectieField;
            }
            set
            {
                this.IsCorrectieField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal bool NegeerRrInformatie
        {
            get
            {
                return this.NegeerRrInformatieField;
            }
            set
            {
                this.NegeerRrInformatieField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal CrabWrite.RrStraat[] RrStraten
        {
            get
            {
                return this.RrStratenField;
            }
            set
            {
                this.RrStratenField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string Status
        {
            get
            {
                return this.StatusField;
            }
            set
            {
                this.StatusField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string Straatnaam
        {
            get
            {
                return this.StraatnaamField;
            }
            set
            {
                this.StraatnaamField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string Straatnaam2
        {
            get
            {
                return this.Straatnaam2Field;
            }
            set
            {
                this.Straatnaam2Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal CrabWrite.Wegkant[] Wegkanten
        {
            get
            {
                return this.WegkantenField;
            }
            set
            {
                this.WegkantenField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30514-0828")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UpdateAdresRequest", Namespace="http://Gisvl.CrabDecentraal.CrabEdit")]
    internal partial class UpdateAdresRequest : object
    {
        
        private System.DateTime BegindatumField;
        
        private CrabWrite.BestaandGebouw[] BestaandeGebouwenField;
        
        private CrabWrite.BestaandPerceel[] BestaandePercelenField;
        
        private string HuisnummerField;
        
        private int IdField;
        
        private bool IsCorrectieField;
        
        private bool NegeerRrInformatieField;
        
        private CrabWrite.NieuwGebouw[] NieuweGebouwenField;
        
        private CrabWrite.Adrespositie[] PositiesField;
        
        private string PostcodeField;
        
        private CrabWrite.RrAdres RrAdresField;
        
        private string StatusField;
        
        private CrabWrite.Subadres[] SubadressenField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal System.DateTime Begindatum
        {
            get
            {
                return this.BegindatumField;
            }
            set
            {
                this.BegindatumField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal CrabWrite.BestaandGebouw[] BestaandeGebouwen
        {
            get
            {
                return this.BestaandeGebouwenField;
            }
            set
            {
                this.BestaandeGebouwenField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal CrabWrite.BestaandPerceel[] BestaandePercelen
        {
            get
            {
                return this.BestaandePercelenField;
            }
            set
            {
                this.BestaandePercelenField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string Huisnummer
        {
            get
            {
                return this.HuisnummerField;
            }
            set
            {
                this.HuisnummerField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal int Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal bool IsCorrectie
        {
            get
            {
                return this.IsCorrectieField;
            }
            set
            {
                this.IsCorrectieField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal bool NegeerRrInformatie
        {
            get
            {
                return this.NegeerRrInformatieField;
            }
            set
            {
                this.NegeerRrInformatieField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal CrabWrite.NieuwGebouw[] NieuweGebouwen
        {
            get
            {
                return this.NieuweGebouwenField;
            }
            set
            {
                this.NieuweGebouwenField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal CrabWrite.Adrespositie[] Posities
        {
            get
            {
                return this.PositiesField;
            }
            set
            {
                this.PositiesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string Postcode
        {
            get
            {
                return this.PostcodeField;
            }
            set
            {
                this.PostcodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal CrabWrite.RrAdres RrAdres
        {
            get
            {
                return this.RrAdresField;
            }
            set
            {
                this.RrAdresField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string Status
        {
            get
            {
                return this.StatusField;
            }
            set
            {
                this.StatusField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal CrabWrite.Subadres[] Subadressen
        {
            get
            {
                return this.SubadressenField;
            }
            set
            {
                this.SubadressenField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30514-0828")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UpdateSubadresRequest", Namespace="http://Gisvl.CrabDecentraal.CrabEdit")]
    internal partial class UpdateSubadresRequest : object
    {
        
        private string AppnummerField;
        
        private System.DateTime BegindatumField;
        
        private string BusnummerField;
        
        private int IdField;
        
        private bool IsCorrectieField;
        
        private bool NegeerRrInformatieField;
        
        private CrabWrite.Adrespositie[] PositiesField;
        
        private CrabWrite.RrAdres RrAdresField;
        
        private string StatusField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string Appnummer
        {
            get
            {
                return this.AppnummerField;
            }
            set
            {
                this.AppnummerField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal System.DateTime Begindatum
        {
            get
            {
                return this.BegindatumField;
            }
            set
            {
                this.BegindatumField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string Busnummer
        {
            get
            {
                return this.BusnummerField;
            }
            set
            {
                this.BusnummerField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal int Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal bool IsCorrectie
        {
            get
            {
                return this.IsCorrectieField;
            }
            set
            {
                this.IsCorrectieField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal bool NegeerRrInformatie
        {
            get
            {
                return this.NegeerRrInformatieField;
            }
            set
            {
                this.NegeerRrInformatieField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal CrabWrite.Adrespositie[] Posities
        {
            get
            {
                return this.PositiesField;
            }
            set
            {
                this.PositiesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal CrabWrite.RrAdres RrAdres
        {
            get
            {
                return this.RrAdresField;
            }
            set
            {
                this.RrAdresField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string Status
        {
            get
            {
                return this.StatusField;
            }
            set
            {
                this.StatusField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30514-0828")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UpdateGebouwRequest", Namespace="http://Gisvl.CrabDecentraal.CrabEdit")]
    internal partial class UpdateGebouwRequest : object
    {
        
        private string AardGebouwField;
        
        private System.DateTime BegindatumField;
        
        private string GeometriemethodeField;
        
        private int IdField;
        
        private bool IsCorrectieField;
        
        private string StatusField;
        
        private string WktField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string AardGebouw
        {
            get
            {
                return this.AardGebouwField;
            }
            set
            {
                this.AardGebouwField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal System.DateTime Begindatum
        {
            get
            {
                return this.BegindatumField;
            }
            set
            {
                this.BegindatumField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string Geometriemethode
        {
            get
            {
                return this.GeometriemethodeField;
            }
            set
            {
                this.GeometriemethodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal int Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal bool IsCorrectie
        {
            get
            {
                return this.IsCorrectieField;
            }
            set
            {
                this.IsCorrectieField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string Status
        {
            get
            {
                return this.StatusField;
            }
            set
            {
                this.StatusField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string Wkt
        {
            get
            {
                return this.WktField;
            }
            set
            {
                this.WktField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30514-0828")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UpdateWegverbindingRequest", Namespace="http://Gisvl.CrabDecentraal.CrabEdit")]
    internal partial class UpdateWegverbindingRequest : object
    {
        
        private System.DateTime BegindatumField;
        
        private string GeometriemethodeField;
        
        private int IdField;
        
        private bool IsCorrectieField;
        
        private string MorfologieField;
        
        private string StatusField;
        
        private string VerhardingField;
        
        private string WktField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal System.DateTime Begindatum
        {
            get
            {
                return this.BegindatumField;
            }
            set
            {
                this.BegindatumField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string Geometriemethode
        {
            get
            {
                return this.GeometriemethodeField;
            }
            set
            {
                this.GeometriemethodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal int Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal bool IsCorrectie
        {
            get
            {
                return this.IsCorrectieField;
            }
            set
            {
                this.IsCorrectieField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string Morfologie
        {
            get
            {
                return this.MorfologieField;
            }
            set
            {
                this.MorfologieField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string Status
        {
            get
            {
                return this.StatusField;
            }
            set
            {
                this.StatusField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string Verharding
        {
            get
            {
                return this.VerhardingField;
            }
            set
            {
                this.VerhardingField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string Wkt
        {
            get
            {
                return this.WktField;
            }
            set
            {
                this.WktField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30514-0828")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RenumberingRequest", Namespace="http://Gisvl.CrabDecentraal.CrabEdit")]
    internal partial class RenumberingRequest : object
    {
        
        private System.DateTime DatumField;
        
        private bool EndOldAddressesField;
        
        private CrabWrite.RenumberingLine[] RenumberingLinesField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal System.DateTime Datum
        {
            get
            {
                return this.DatumField;
            }
            set
            {
                this.DatumField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal bool EndOldAddresses
        {
            get
            {
                return this.EndOldAddressesField;
            }
            set
            {
                this.EndOldAddressesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal CrabWrite.RenumberingLine[] RenumberingLines
        {
            get
            {
                return this.RenumberingLinesField;
            }
            set
            {
                this.RenumberingLinesField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30514-0828")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RenumberingLine", Namespace="http://Gisvl.CrabDecentraal.CrabEdit")]
    internal partial class RenumberingLine : object
    {
        
        private int AdresIdField;
        
        private string HuisnummerField;
        
        private string StraatnaamField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal int AdresId
        {
            get
            {
                return this.AdresIdField;
            }
            set
            {
                this.AdresIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string Huisnummer
        {
            get
            {
                return this.HuisnummerField;
            }
            set
            {
                this.HuisnummerField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string Straatnaam
        {
            get
            {
                return this.StraatnaamField;
            }
            set
            {
                this.StraatnaamField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30514-0828")]
    [System.Runtime.Serialization.DataContractAttribute(Name="VerdachtGevalQuery", Namespace="http://Gisvl.CrabDecentraal.CrabEdit")]
    internal partial class VerdachtGevalQuery : object
    {
        
        private string EntiteitTypeField;
        
        private string InstructieField;
        
        private string LabelHoofdingField;
        
        private string OmschrijvingField;
        
        private int QueryIdField;
        
        private string ValidatieTypeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string EntiteitType
        {
            get
            {
                return this.EntiteitTypeField;
            }
            set
            {
                this.EntiteitTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string Instructie
        {
            get
            {
                return this.InstructieField;
            }
            set
            {
                this.InstructieField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string LabelHoofding
        {
            get
            {
                return this.LabelHoofdingField;
            }
            set
            {
                this.LabelHoofdingField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string Omschrijving
        {
            get
            {
                return this.OmschrijvingField;
            }
            set
            {
                this.OmschrijvingField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal int QueryId
        {
            get
            {
                return this.QueryIdField;
            }
            set
            {
                this.QueryIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string ValidatieType
        {
            get
            {
                return this.ValidatieTypeField;
            }
            set
            {
                this.ValidatieTypeField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30514-0828")]
    [System.Runtime.Serialization.DataContractAttribute(Name="VerdachtGeval", Namespace="http://Gisvl.CrabDecentraal.CrabEdit")]
    internal partial class VerdachtGeval : object
    {
        
        private int EntiteitIdField;
        
        private string LabelField;
        
        private int VolgNummerField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal int EntiteitId
        {
            get
            {
                return this.EntiteitIdField;
            }
            set
            {
                this.EntiteitIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string Label
        {
            get
            {
                return this.LabelField;
            }
            set
            {
                this.LabelField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal int VolgNummer
        {
            get
            {
                return this.VolgNummerField;
            }
            set
            {
                this.VolgNummerField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30514-0828")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PagedListVerdachteGevallen", Namespace="http://Gisvl.CrabDecentraal.CrabEdit")]
    internal partial class PagedListVerdachteGevallen : object
    {
        
        private int TotaalAantalGevallenField;
        
        private CrabWrite.VerdachtGeval[] VerdachteGevallenField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal int TotaalAantalGevallen
        {
            get
            {
                return this.TotaalAantalGevallenField;
            }
            set
            {
                this.TotaalAantalGevallenField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal CrabWrite.VerdachtGeval[] VerdachteGevallen
        {
            get
            {
                return this.VerdachteGevallenField;
            }
            set
            {
                this.VerdachteGevallenField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30514-0828")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MaskRequest", Namespace="http://Gisvl.CrabDecentraal.CrabEdit")]
    internal partial class MaskRequest : object
    {
        
        private int[] EntiteitIdsField;
        
        private int QueryIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal int[] EntiteitIds
        {
            get
            {
                return this.EntiteitIdsField;
            }
            set
            {
                this.EntiteitIdsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal int QueryId
        {
            get
            {
                return this.QueryIdField;
            }
            set
            {
                this.QueryIdField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30514-0828")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Beheerder", Namespace="http://Gisvl.CrabDecentraal.CrabEdit")]
    internal partial class Beheerder : object
    {
        
        private string GemeenteField;
        
        private string NameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string Gemeente
        {
            get
            {
                return this.GemeenteField;
            }
            set
            {
                this.GemeenteField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30514-0828")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Transactie", Namespace="http://Gisvl.CrabDecentraal.CrabEdit")]
    internal partial class Transactie : object
    {
        
        private string BeheerderField;
        
        private string BeschrijvingField;
        
        private CrabWrite.CrabEntityType CrabEntiteitTypeField;
        
        private int EntiteitIdField;
        
        private System.DateTime TijdstipField;
        
        private CrabWrite.TransactionType TransactieTypeField;
        
        private int VolgnummerField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string Beheerder
        {
            get
            {
                return this.BeheerderField;
            }
            set
            {
                this.BeheerderField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string Beschrijving
        {
            get
            {
                return this.BeschrijvingField;
            }
            set
            {
                this.BeschrijvingField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal CrabWrite.CrabEntityType CrabEntiteitType
        {
            get
            {
                return this.CrabEntiteitTypeField;
            }
            set
            {
                this.CrabEntiteitTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal int EntiteitId
        {
            get
            {
                return this.EntiteitIdField;
            }
            set
            {
                this.EntiteitIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal System.DateTime Tijdstip
        {
            get
            {
                return this.TijdstipField;
            }
            set
            {
                this.TijdstipField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal CrabWrite.TransactionType TransactieType
        {
            get
            {
                return this.TransactieTypeField;
            }
            set
            {
                this.TransactieTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal int Volgnummer
        {
            get
            {
                return this.VolgnummerField;
            }
            set
            {
                this.VolgnummerField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30514-0828")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CrabEntityType", Namespace="http://Gisvl.CrabDecentraal.CrabEdit")]
    internal enum CrabEntityType : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Adres = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Gebouw = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Perceel = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Straat = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Wegverbinding = 5,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        RrAdres = 6,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        RrStraat = 7,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30514-0828")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TransactionType", Namespace="http://Gisvl.CrabDecentraal.CrabEdit")]
    internal enum TransactionType : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Invoer = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Correctie = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Historering = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Verwijdering = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Hernummering = 5,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30514-0828")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TransactieAggregaat", Namespace="http://schemas.datacontract.org/2004/07/Gisvl.CrabDecentraal.EditContract.Dto")]
    internal partial class TransactieAggregaat : object
    {
        
        private int AantalField;
        
        private CrabWrite.CrabEntityType CrabEntiteitTypeField;
        
        private CrabWrite.TransactionType TransactieTypeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal int Aantal
        {
            get
            {
                return this.AantalField;
            }
            set
            {
                this.AantalField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal CrabWrite.CrabEntityType CrabEntiteitType
        {
            get
            {
                return this.CrabEntiteitTypeField;
            }
            set
            {
                this.CrabEntiteitTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal CrabWrite.TransactionType TransactieType
        {
            get
            {
                return this.TransactieTypeField;
            }
            set
            {
                this.TransactieTypeField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30514-0828")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://Gisvl.CrabDecentraal.CrabEdit", ConfigurationName="CrabWrite.ICrabEdit")]
    internal interface ICrabEdit
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Gisvl.CrabDecentraal.CrabEdit/ICrabEdit/GetGemeenteOmtrek", ReplyAction="http://Gisvl.CrabDecentraal.CrabEdit/ICrabEdit/GetGemeenteOmtrekResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(CrabWrite.FaultDetail), Action="http://Gisvl.CrabDecentraal.CrabEdit/ICrabEdit/GetGemeenteOmtrekFaultDetailFault", Name="FaultDetail", Namespace="http://www.agiv.be/ErrorHandling/2010/04")]
        System.Threading.Tasks.Task<string> GetGemeenteOmtrekAsync(string gemeente);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Gisvl.CrabDecentraal.CrabEdit/ICrabEdit/AddStraat", ReplyAction="http://Gisvl.CrabDecentraal.CrabEdit/ICrabEdit/AddStraatResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(CrabWrite.FaultDetail), Action="http://Gisvl.CrabDecentraal.CrabEdit/ICrabEdit/AddStraatFaultDetailFault", Name="FaultDetail", Namespace="http://www.agiv.be/ErrorHandling/2010/04")]
        System.Threading.Tasks.Task<int> AddStraatAsync(CrabWrite.AddStraatRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Gisvl.CrabDecentraal.CrabEdit/ICrabEdit/AddAdres", ReplyAction="http://Gisvl.CrabDecentraal.CrabEdit/ICrabEdit/AddAdresResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(CrabWrite.FaultDetail), Action="http://Gisvl.CrabDecentraal.CrabEdit/ICrabEdit/AddAdresFaultDetailFault", Name="FaultDetail", Namespace="http://www.agiv.be/ErrorHandling/2010/04")]
        System.Threading.Tasks.Task<int> AddAdresAsync(CrabWrite.AddAdresRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Gisvl.CrabDecentraal.CrabEdit/ICrabEdit/AddGebouw", ReplyAction="http://Gisvl.CrabDecentraal.CrabEdit/ICrabEdit/AddGebouwResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(CrabWrite.FaultDetail), Action="http://Gisvl.CrabDecentraal.CrabEdit/ICrabEdit/AddGebouwFaultDetailFault", Name="FaultDetail", Namespace="http://www.agiv.be/ErrorHandling/2010/04")]
        System.Threading.Tasks.Task<int> AddGebouwAsync(CrabWrite.AddGebouwRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Gisvl.CrabDecentraal.CrabEdit/ICrabEdit/AddWegverbinding", ReplyAction="http://Gisvl.CrabDecentraal.CrabEdit/ICrabEdit/AddWegverbindingResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(CrabWrite.FaultDetail), Action="http://Gisvl.CrabDecentraal.CrabEdit/ICrabEdit/AddWegverbindingFaultDetailFault", Name="FaultDetail", Namespace="http://www.agiv.be/ErrorHandling/2010/04")]
        System.Threading.Tasks.Task<int> AddWegverbindingAsync(CrabWrite.AddWegverbindingRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Gisvl.CrabDecentraal.CrabEdit/ICrabEdit/UpdateStraat", ReplyAction="http://Gisvl.CrabDecentraal.CrabEdit/ICrabEdit/UpdateStraatResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(CrabWrite.FaultDetail), Action="http://Gisvl.CrabDecentraal.CrabEdit/ICrabEdit/UpdateStraatFaultDetailFault", Name="FaultDetail", Namespace="http://www.agiv.be/ErrorHandling/2010/04")]
        System.Threading.Tasks.Task<int> UpdateStraatAsync(CrabWrite.UpdateStraatRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Gisvl.CrabDecentraal.CrabEdit/ICrabEdit/UpdateAdres", ReplyAction="http://Gisvl.CrabDecentraal.CrabEdit/ICrabEdit/UpdateAdresResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(CrabWrite.FaultDetail), Action="http://Gisvl.CrabDecentraal.CrabEdit/ICrabEdit/UpdateAdresFaultDetailFault", Name="FaultDetail", Namespace="http://www.agiv.be/ErrorHandling/2010/04")]
        System.Threading.Tasks.Task<int> UpdateAdresAsync(CrabWrite.UpdateAdresRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Gisvl.CrabDecentraal.CrabEdit/ICrabEdit/UpdateSubadres", ReplyAction="http://Gisvl.CrabDecentraal.CrabEdit/ICrabEdit/UpdateSubadresResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(CrabWrite.FaultDetail), Action="http://Gisvl.CrabDecentraal.CrabEdit/ICrabEdit/UpdateSubadresFaultDetailFault", Name="FaultDetail", Namespace="http://www.agiv.be/ErrorHandling/2010/04")]
        System.Threading.Tasks.Task<int> UpdateSubadresAsync(CrabWrite.UpdateSubadresRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Gisvl.CrabDecentraal.CrabEdit/ICrabEdit/UpdateGebouw", ReplyAction="http://Gisvl.CrabDecentraal.CrabEdit/ICrabEdit/UpdateGebouwResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(CrabWrite.FaultDetail), Action="http://Gisvl.CrabDecentraal.CrabEdit/ICrabEdit/UpdateGebouwFaultDetailFault", Name="FaultDetail", Namespace="http://www.agiv.be/ErrorHandling/2010/04")]
        System.Threading.Tasks.Task<int> UpdateGebouwAsync(CrabWrite.UpdateGebouwRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Gisvl.CrabDecentraal.CrabEdit/ICrabEdit/UpdateWegverbinding", ReplyAction="http://Gisvl.CrabDecentraal.CrabEdit/ICrabEdit/UpdateWegverbindingResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(CrabWrite.FaultDetail), Action="http://Gisvl.CrabDecentraal.CrabEdit/ICrabEdit/UpdateWegverbindingFaultDetailFaul" +
            "t", Name="FaultDetail", Namespace="http://www.agiv.be/ErrorHandling/2010/04")]
        System.Threading.Tasks.Task<int> UpdateWegverbindingAsync(CrabWrite.UpdateWegverbindingRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Gisvl.CrabDecentraal.CrabEdit/ICrabEdit/DeleteStraat", ReplyAction="http://Gisvl.CrabDecentraal.CrabEdit/ICrabEdit/DeleteStraatResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(CrabWrite.FaultDetail), Action="http://Gisvl.CrabDecentraal.CrabEdit/ICrabEdit/DeleteStraatFaultDetailFault", Name="FaultDetail", Namespace="http://www.agiv.be/ErrorHandling/2010/04")]
        System.Threading.Tasks.Task DeleteStraatAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Gisvl.CrabDecentraal.CrabEdit/ICrabEdit/DeleteAdres", ReplyAction="http://Gisvl.CrabDecentraal.CrabEdit/ICrabEdit/DeleteAdresResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(CrabWrite.FaultDetail), Action="http://Gisvl.CrabDecentraal.CrabEdit/ICrabEdit/DeleteAdresFaultDetailFault", Name="FaultDetail", Namespace="http://www.agiv.be/ErrorHandling/2010/04")]
        System.Threading.Tasks.Task DeleteAdresAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Gisvl.CrabDecentraal.CrabEdit/ICrabEdit/DeleteGebouw", ReplyAction="http://Gisvl.CrabDecentraal.CrabEdit/ICrabEdit/DeleteGebouwResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(CrabWrite.FaultDetail), Action="http://Gisvl.CrabDecentraal.CrabEdit/ICrabEdit/DeleteGebouwFaultDetailFault", Name="FaultDetail", Namespace="http://www.agiv.be/ErrorHandling/2010/04")]
        System.Threading.Tasks.Task DeleteGebouwAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Gisvl.CrabDecentraal.CrabEdit/ICrabEdit/DeleteWegverbinding", ReplyAction="http://Gisvl.CrabDecentraal.CrabEdit/ICrabEdit/DeleteWegverbindingResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(CrabWrite.FaultDetail), Action="http://Gisvl.CrabDecentraal.CrabEdit/ICrabEdit/DeleteWegverbindingFaultDetailFaul" +
            "t", Name="FaultDetail", Namespace="http://www.agiv.be/ErrorHandling/2010/04")]
        System.Threading.Tasks.Task DeleteWegverbindingAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Gisvl.CrabDecentraal.CrabEdit/ICrabEdit/EndStraat", ReplyAction="http://Gisvl.CrabDecentraal.CrabEdit/ICrabEdit/EndStraatResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(CrabWrite.FaultDetail), Action="http://Gisvl.CrabDecentraal.CrabEdit/ICrabEdit/EndStraatFaultDetailFault", Name="FaultDetail", Namespace="http://www.agiv.be/ErrorHandling/2010/04")]
        System.Threading.Tasks.Task EndStraatAsync(int id, System.DateTime endDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Gisvl.CrabDecentraal.CrabEdit/ICrabEdit/EndAdres", ReplyAction="http://Gisvl.CrabDecentraal.CrabEdit/ICrabEdit/EndAdresResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(CrabWrite.FaultDetail), Action="http://Gisvl.CrabDecentraal.CrabEdit/ICrabEdit/EndAdresFaultDetailFault", Name="FaultDetail", Namespace="http://www.agiv.be/ErrorHandling/2010/04")]
        System.Threading.Tasks.Task EndAdresAsync(int id, System.DateTime endDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Gisvl.CrabDecentraal.CrabEdit/ICrabEdit/EndGebouw", ReplyAction="http://Gisvl.CrabDecentraal.CrabEdit/ICrabEdit/EndGebouwResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(CrabWrite.FaultDetail), Action="http://Gisvl.CrabDecentraal.CrabEdit/ICrabEdit/EndGebouwFaultDetailFault", Name="FaultDetail", Namespace="http://www.agiv.be/ErrorHandling/2010/04")]
        System.Threading.Tasks.Task EndGebouwAsync(int id, System.DateTime endDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Gisvl.CrabDecentraal.CrabEdit/ICrabEdit/EndWegverbinding", ReplyAction="http://Gisvl.CrabDecentraal.CrabEdit/ICrabEdit/EndWegverbindingResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(CrabWrite.FaultDetail), Action="http://Gisvl.CrabDecentraal.CrabEdit/ICrabEdit/EndWegverbindingFaultDetailFault", Name="FaultDetail", Namespace="http://www.agiv.be/ErrorHandling/2010/04")]
        System.Threading.Tasks.Task EndWegverbindingAsync(int id, System.DateTime endDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Gisvl.CrabDecentraal.CrabEdit/ICrabEdit/PerformRenumbering", ReplyAction="http://Gisvl.CrabDecentraal.CrabEdit/ICrabEdit/PerformRenumberingResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(CrabWrite.FaultDetail), Action="http://Gisvl.CrabDecentraal.CrabEdit/ICrabEdit/PerformRenumberingFaultDetailFault" +
            "", Name="FaultDetail", Namespace="http://www.agiv.be/ErrorHandling/2010/04")]
        System.Threading.Tasks.Task PerformRenumberingAsync(CrabWrite.RenumberingRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Gisvl.CrabDecentraal.CrabEdit/ICrabEdit/ListVerdachteGevallenQueries", ReplyAction="http://Gisvl.CrabDecentraal.CrabEdit/ICrabEdit/ListVerdachteGevallenQueriesRespon" +
            "se")]
        [System.ServiceModel.FaultContractAttribute(typeof(CrabWrite.FaultDetail), Action="http://Gisvl.CrabDecentraal.CrabEdit/ICrabEdit/ListVerdachteGevallenQueriesFaultD" +
            "etailFault", Name="FaultDetail", Namespace="http://www.agiv.be/ErrorHandling/2010/04")]
        System.Threading.Tasks.Task<CrabWrite.VerdachtGevalQuery[]> ListVerdachteGevallenQueriesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Gisvl.CrabDecentraal.CrabEdit/ICrabEdit/CountVerdachteGevallenByQueryId", ReplyAction="http://Gisvl.CrabDecentraal.CrabEdit/ICrabEdit/CountVerdachteGevallenByQueryIdRes" +
            "ponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(CrabWrite.FaultDetail), Action="http://Gisvl.CrabDecentraal.CrabEdit/ICrabEdit/CountVerdachteGevallenByQueryIdFau" +
            "ltDetailFault", Name="FaultDetail", Namespace="http://www.agiv.be/ErrorHandling/2010/04")]
        System.Threading.Tasks.Task<int> CountVerdachteGevallenByQueryIdAsync(int queryId, string gemeente);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Gisvl.CrabDecentraal.CrabEdit/ICrabEdit/ListVerdachteGevallenByQueryId", ReplyAction="http://Gisvl.CrabDecentraal.CrabEdit/ICrabEdit/ListVerdachteGevallenByQueryIdResp" +
            "onse")]
        [System.ServiceModel.FaultContractAttribute(typeof(CrabWrite.FaultDetail), Action="http://Gisvl.CrabDecentraal.CrabEdit/ICrabEdit/ListVerdachteGevallenByQueryIdFaul" +
            "tDetailFault", Name="FaultDetail", Namespace="http://www.agiv.be/ErrorHandling/2010/04")]
        System.Threading.Tasks.Task<CrabWrite.VerdachtGeval[]> ListVerdachteGevallenByQueryIdAsync(int queryId, string gemeente);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Gisvl.CrabDecentraal.CrabEdit/ICrabEdit/ListVerdachteGevallenByQueryIdPage" +
            "d", ReplyAction="http://Gisvl.CrabDecentraal.CrabEdit/ICrabEdit/ListVerdachteGevallenByQueryIdPage" +
            "dResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(CrabWrite.FaultDetail), Action="http://Gisvl.CrabDecentraal.CrabEdit/ICrabEdit/ListVerdachteGevallenByQueryIdPage" +
            "dFaultDetailFault", Name="FaultDetail", Namespace="http://www.agiv.be/ErrorHandling/2010/04")]
        System.Threading.Tasks.Task<CrabWrite.PagedListVerdachteGevallen> ListVerdachteGevallenByQueryIdPagedAsync(int queryId, int pageSize, int pageIndex, string gemeente);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Gisvl.CrabDecentraal.CrabEdit/ICrabEdit/MaskVerdachteGevallen", ReplyAction="http://Gisvl.CrabDecentraal.CrabEdit/ICrabEdit/MaskVerdachteGevallenResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(CrabWrite.FaultDetail), Action="http://Gisvl.CrabDecentraal.CrabEdit/ICrabEdit/MaskVerdachteGevallenFaultDetailFa" +
            "ult", Name="FaultDetail", Namespace="http://www.agiv.be/ErrorHandling/2010/04")]
        System.Threading.Tasks.Task MaskVerdachteGevallenAsync(CrabWrite.MaskRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Gisvl.CrabDecentraal.CrabEdit/ICrabEdit/ListBeheerdersByGemeente", ReplyAction="http://Gisvl.CrabDecentraal.CrabEdit/ICrabEdit/ListBeheerdersByGemeenteResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(CrabWrite.FaultDetail), Action="http://Gisvl.CrabDecentraal.CrabEdit/ICrabEdit/ListBeheerdersByGemeenteFaultDetai" +
            "lFault", Name="FaultDetail", Namespace="http://www.agiv.be/ErrorHandling/2010/04")]
        System.Threading.Tasks.Task<CrabWrite.Beheerder[]> ListBeheerdersByGemeenteAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Gisvl.CrabDecentraal.CrabEdit/ICrabEdit/ListTransacties", ReplyAction="http://Gisvl.CrabDecentraal.CrabEdit/ICrabEdit/ListTransactiesResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(CrabWrite.FaultDetail), Action="http://Gisvl.CrabDecentraal.CrabEdit/ICrabEdit/ListTransactiesFaultDetailFault", Name="FaultDetail", Namespace="http://www.agiv.be/ErrorHandling/2010/04")]
        System.Threading.Tasks.Task<CrabWrite.Transactie[]> ListTransactiesAsync(string gemeente, string beheerder, System.DateTime tijdstip1, System.DateTime tijdstip2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Gisvl.CrabDecentraal.CrabEdit/ICrabEdit/ListTransactiesPaged", ReplyAction="http://Gisvl.CrabDecentraal.CrabEdit/ICrabEdit/ListTransactiesPagedResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(CrabWrite.FaultDetail), Action="http://Gisvl.CrabDecentraal.CrabEdit/ICrabEdit/ListTransactiesPagedFaultDetailFau" +
            "lt", Name="FaultDetail", Namespace="http://www.agiv.be/ErrorHandling/2010/04")]
        System.Threading.Tasks.Task<CrabWrite.Transactie[]> ListTransactiesPagedAsync(string gemeente, string beheerder, System.DateTime tijdstip1, System.DateTime tijdstip2, int pageSize, int pageIndex);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Gisvl.CrabDecentraal.CrabEdit/ICrabEdit/ListTransactieAggregaten", ReplyAction="http://Gisvl.CrabDecentraal.CrabEdit/ICrabEdit/ListTransactieAggregatenResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(CrabWrite.FaultDetail), Action="http://Gisvl.CrabDecentraal.CrabEdit/ICrabEdit/ListTransactieAggregatenFaultDetai" +
            "lFault", Name="FaultDetail", Namespace="http://www.agiv.be/ErrorHandling/2010/04")]
        System.Threading.Tasks.Task<CrabWrite.TransactieAggregaat[]> ListTransactieAggregatenAsync(string gemeente, string beheerder, System.DateTime tijdstip1, System.DateTime tijdstip2);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30514-0828")]
    internal interface ICrabEditChannel : CrabWrite.ICrabEdit, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30514-0828")]
    internal partial class CrabEditClient : System.ServiceModel.ClientBase<CrabWrite.ICrabEdit>, CrabWrite.ICrabEdit
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public CrabEditClient() : 
                base(CrabEditClient.GetDefaultBinding(), CrabEditClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_ICrabEdit.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public CrabEditClient(EndpointConfiguration endpointConfiguration) : 
                base(CrabEditClient.GetBindingForEndpoint(endpointConfiguration), CrabEditClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public CrabEditClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(CrabEditClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public CrabEditClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(CrabEditClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public CrabEditClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<string> GetGemeenteOmtrekAsync(string gemeente)
        {
            return base.Channel.GetGemeenteOmtrekAsync(gemeente);
        }
        
        public System.Threading.Tasks.Task<int> AddStraatAsync(CrabWrite.AddStraatRequest request)
        {
            return base.Channel.AddStraatAsync(request);
        }
        
        public System.Threading.Tasks.Task<int> AddAdresAsync(CrabWrite.AddAdresRequest request)
        {
            return base.Channel.AddAdresAsync(request);
        }
        
        public System.Threading.Tasks.Task<int> AddGebouwAsync(CrabWrite.AddGebouwRequest request)
        {
            return base.Channel.AddGebouwAsync(request);
        }
        
        public System.Threading.Tasks.Task<int> AddWegverbindingAsync(CrabWrite.AddWegverbindingRequest request)
        {
            return base.Channel.AddWegverbindingAsync(request);
        }
        
        public System.Threading.Tasks.Task<int> UpdateStraatAsync(CrabWrite.UpdateStraatRequest request)
        {
            return base.Channel.UpdateStraatAsync(request);
        }
        
        public System.Threading.Tasks.Task<int> UpdateAdresAsync(CrabWrite.UpdateAdresRequest request)
        {
            return base.Channel.UpdateAdresAsync(request);
        }
        
        public System.Threading.Tasks.Task<int> UpdateSubadresAsync(CrabWrite.UpdateSubadresRequest request)
        {
            return base.Channel.UpdateSubadresAsync(request);
        }
        
        public System.Threading.Tasks.Task<int> UpdateGebouwAsync(CrabWrite.UpdateGebouwRequest request)
        {
            return base.Channel.UpdateGebouwAsync(request);
        }
        
        public System.Threading.Tasks.Task<int> UpdateWegverbindingAsync(CrabWrite.UpdateWegverbindingRequest request)
        {
            return base.Channel.UpdateWegverbindingAsync(request);
        }
        
        public System.Threading.Tasks.Task DeleteStraatAsync(int id)
        {
            return base.Channel.DeleteStraatAsync(id);
        }
        
        public System.Threading.Tasks.Task DeleteAdresAsync(int id)
        {
            return base.Channel.DeleteAdresAsync(id);
        }
        
        public System.Threading.Tasks.Task DeleteGebouwAsync(int id)
        {
            return base.Channel.DeleteGebouwAsync(id);
        }
        
        public System.Threading.Tasks.Task DeleteWegverbindingAsync(int id)
        {
            return base.Channel.DeleteWegverbindingAsync(id);
        }
        
        public System.Threading.Tasks.Task EndStraatAsync(int id, System.DateTime endDate)
        {
            return base.Channel.EndStraatAsync(id, endDate);
        }
        
        public System.Threading.Tasks.Task EndAdresAsync(int id, System.DateTime endDate)
        {
            return base.Channel.EndAdresAsync(id, endDate);
        }
        
        public System.Threading.Tasks.Task EndGebouwAsync(int id, System.DateTime endDate)
        {
            return base.Channel.EndGebouwAsync(id, endDate);
        }
        
        public System.Threading.Tasks.Task EndWegverbindingAsync(int id, System.DateTime endDate)
        {
            return base.Channel.EndWegverbindingAsync(id, endDate);
        }
        
        public System.Threading.Tasks.Task PerformRenumberingAsync(CrabWrite.RenumberingRequest request)
        {
            return base.Channel.PerformRenumberingAsync(request);
        }
        
        public System.Threading.Tasks.Task<CrabWrite.VerdachtGevalQuery[]> ListVerdachteGevallenQueriesAsync()
        {
            return base.Channel.ListVerdachteGevallenQueriesAsync();
        }
        
        public System.Threading.Tasks.Task<int> CountVerdachteGevallenByQueryIdAsync(int queryId, string gemeente)
        {
            return base.Channel.CountVerdachteGevallenByQueryIdAsync(queryId, gemeente);
        }
        
        public System.Threading.Tasks.Task<CrabWrite.VerdachtGeval[]> ListVerdachteGevallenByQueryIdAsync(int queryId, string gemeente)
        {
            return base.Channel.ListVerdachteGevallenByQueryIdAsync(queryId, gemeente);
        }
        
        public System.Threading.Tasks.Task<CrabWrite.PagedListVerdachteGevallen> ListVerdachteGevallenByQueryIdPagedAsync(int queryId, int pageSize, int pageIndex, string gemeente)
        {
            return base.Channel.ListVerdachteGevallenByQueryIdPagedAsync(queryId, pageSize, pageIndex, gemeente);
        }
        
        public System.Threading.Tasks.Task MaskVerdachteGevallenAsync(CrabWrite.MaskRequest request)
        {
            return base.Channel.MaskVerdachteGevallenAsync(request);
        }
        
        public System.Threading.Tasks.Task<CrabWrite.Beheerder[]> ListBeheerdersByGemeenteAsync()
        {
            return base.Channel.ListBeheerdersByGemeenteAsync();
        }
        
        public System.Threading.Tasks.Task<CrabWrite.Transactie[]> ListTransactiesAsync(string gemeente, string beheerder, System.DateTime tijdstip1, System.DateTime tijdstip2)
        {
            return base.Channel.ListTransactiesAsync(gemeente, beheerder, tijdstip1, tijdstip2);
        }
        
        public System.Threading.Tasks.Task<CrabWrite.Transactie[]> ListTransactiesPagedAsync(string gemeente, string beheerder, System.DateTime tijdstip1, System.DateTime tijdstip2, int pageSize, int pageIndex)
        {
            return base.Channel.ListTransactiesPagedAsync(gemeente, beheerder, tijdstip1, tijdstip2, pageSize, pageIndex);
        }
        
        public System.Threading.Tasks.Task<CrabWrite.TransactieAggregaat[]> ListTransactieAggregatenAsync(string gemeente, string beheerder, System.DateTime tijdstip1, System.DateTime tijdstip2)
        {
            return base.Channel.ListTransactieAggregatenAsync(gemeente, beheerder, tijdstip1, tijdstip2);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_ICrabEdit))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_ICrabEdit))
            {
                return new System.ServiceModel.EndpointAddress("http://aocsrv124:88/EditOpen/CrabEditService.svc");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return CrabEditClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_ICrabEdit);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return CrabEditClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_ICrabEdit);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_ICrabEdit,
        }
    }
}
